### ISSUE TITLE
admin/announcements/listのクエリがこける

### ISSUE THREAD

**Issue by lqvp** [lqvp/misskey-temp#21]
https://github.com/lqvp/misskey-temp/blob/master/packages/backend/src/server/api/endpoints/admin/announcements/list.ts

```
db-1     | 2024-10-07 01:58:47.377 UTC [1918] ERROR:  syntax error at or near ")" at character 287
db-1     | 2024-10-07 01:58:47.377 UTC [1918] STATEMENT:  SELECT "announcement_role"."announcementId" AS "announcement_role_announcementId", "announcement_role"."roleId" AS "announcement_role_roleId", "announcement_role"."id" AS "announcement_role_id" FROM "announcement_role" "announcement_role" WHERE "announcement_role"."announcementId" IN ()
web-1    | ERR  *       [api]   Internal error occurred in admin/announcements/list: syntax error at or near ")" {
web-1    |   ep: 'admin/announcements/list',
web-1    |   ps: {
web-1    |     userId: '9z1wrswbx2900001',
web-1    |     limit: 10,
web-1    |     allowPartial: true,
web-1    |     i: 'TOKEN',
web-1    |     status: 'active'
web-1    |   },
web-1    |   e: {
web-1    |     message: 'syntax error at or near ")"',
web-1    |     code: 'QueryFailedError',
web-1    |     stack: 'QueryFailedError: syntax error at or near ")"\n' +
web-1    |       '    at PostgresQueryRunner.query (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.13.0/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)\n' +
web-1    |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
web-1    |       '    at async SelectQueryBuilder.loadRawResults (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.13.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)\n' +
web-1    |       '    at async SelectQueryBuilder.executeEntitiesAndRawResults (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.13.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)\n' +
web-1    |       '    at async SelectQueryBuilder.getRawAndEntities (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.13.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)\n' +
web-1    |       '    at async SelectQueryBuilder.getMany (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.13.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)\n' +
web-1    |       '    at async file:///misskey/packages/backend/built/server/api/endpoints/admin/announcements/list.js:168:41\n' +
web-1    |       '    at async ApiCallService.call (file:///misskey/packages/backend/built/server/api/ApiCallService.js:388:20)',
web-1    |     id: 'ae2390d4-a4da-44d4-af36-f842a7f1dceb'
web-1    |   }
web-1    | }
```

**Comment by lqvp** [comment]
使わないってことで
05895c3d9dbedf09e6ecfa8f0c9227dfaddfbc44
